TasksTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: TasksTable2-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: userId
        AttributeType: N
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: userId
        KeyType: HASH
      - AttributeName: id
        KeyType: RANGE